<a href="https://colab.research.google.com/github/Akshay-ramagiri/NLP/blob/main/19K41A0555_NLP_ASSIGNMENT_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
paragraph = '''A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. Almost every piece of writing you do that is longer than a few sentences should be organized into paragraphs. This is because paragraphs show a reader where the subdivisions of an essay begin and end, and thus help the reader see the organization of the essay and grasp its main points. Paragraphs can contain many different kinds of information. A paragraph could contain a series of brief examples or a single long illustration of a general point. It might describe a place, character, or process; narrate a series of events; compare or contrast two or more things; classify items into categories; or describe causes and effects. Regardless of the kind of information they contain, all paragraphs share certain characteristics. One of the most important of these is a topic sentence.'''

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [ ]:
!pip install transformers
!pip install -U sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 85 kB 3.4 MB/s 
     |████████████████████████████████| 1.3 MB 17.7 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=aa30f9a9da6a1313b8ecdf5a5559ca6f986bf3c974c0b5b5de7e2f364665b60e
  Stored in directory: /root/.cache/pip/wheels/bf/06/fb/d59c1e5bd1dac7f6cf61ec0036cc3a10ab8fecaa6b2c3d3ee9
Successfully built sentence-transformers


In [ ]:
import numpy as np
import nltk
import torch
import transformers
import spacy
import tensorflow_hub as hub
import tensorflow.compat.v1 as tf
from spacy import displacy
from nltk.corpus import stopwords
from gensim.models import Word2Vec
from sentence_transformers import SentenceTransformer
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.tokenize import PunktSentenceTokenizer

In [ ]:
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
raw_sentences = tokenizer.tokenize(string.strip())
sentences = [sentence for sentence in raw_sentences if len(sentence) > 0]
print('Sentences :')
print(sentences, end='\n\n\n')

Sentences :
['A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic.', 'Almost every piece of writing you do that is longer than a few sentences should be organized into paragraphs.', 'This is because paragraphs show a reader where the subdivisions of an essay begin and end, and thus help the reader see the organization of the essay and grasp its main points.', 'Paragraphs can contain many different kinds of information.', 'A paragraph could contain a series of brief examples or a single long illustration of a general point.', 'It might describe a place, character, or process; narrate a series of events; compare or contrast two or more things; classify items into categories; or describe causes and effects.', 'Regardless of the kind of information they contain, all paragraphs share certain characteristics.', 'One of the most important of these is a topic sentence.']




#1Q. Paragraph to vector conversion

#i) Word2Vec

In [ ]:
wordvecs = [nltk.word_tokenize(sentence) for sentence in sentences]
stop_words = list(set(stopwords.words("english")))

for sentence in wordvecs:
    for word in sentence:
        if word in stop_words:
            sentence.remove(word)

model = Word2Vec(wordvecs, min_count=1)

# Vector for word 'sentence'
print('Vector for word "sentence" : ')
print(model.wv['sentence'])

Vector for word "sentence" : 
[-4.0985881e-03  2.5022409e-03 -2.2384755e-03 -1.6034958e-03
 -3.4176141e-03 -5.5291143e-04  2.6585665e-03  3.8305251e-03
 -4.1971346e-03 -4.8614764e-03 -2.0855318e-03 -2.9364226e-03
  3.6121262e-03  1.5425925e-04  4.7327527e-03 -8.4750279e-04
 -2.3450674e-03 -1.8456832e-03  3.4886547e-03 -4.8199994e-03
  4.6398239e-03  1.0917144e-03 -4.0146569e-03 -3.3602337e-03
  3.1176112e-03  2.0621060e-03 -7.8777008e-04 -4.5888205e-03
 -2.3103638e-03  8.9275354e-04 -4.1607753e-04 -2.1309645e-03
  6.5786915e-04 -4.1555567e-03  3.8562715e-03  3.4605300e-03
  2.3760905e-03  1.8457241e-03 -4.5100860e-03 -2.3068592e-03
 -2.0730214e-03 -2.7184237e-03 -4.4097737e-03  2.0306299e-03
 -4.7996761e-03  2.0247465e-03  4.4887149e-04 -3.8932844e-03
  4.0041897e-03  9.4471924e-04  2.3475266e-03 -1.7911562e-03
  8.8775507e-04 -1.5242653e-03 -2.9034688e-04 -3.9590491e-04
 -2.6021332e-03 -1.0186937e-03 -2.7952103e-03 -1.1954179e-04
 -4.2321146e-03  7.0736697e-04  1.6208271e-03 -1.966245

#ii) USE

In [ ]:
embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
embeddings = embed(sentences)
print(embeddings, '\n\n')
for i in range(2):
    print('Sentence :')
    print(sentences[i])
    print('Converted to :')
    print(embeddings[i], '\n\n')

tf.Tensor(
[[ 0.01168496 -0.03060572  0.06116336 ... -0.08641755  0.0002505
   0.05482749]
 [ 0.02972507 -0.03655469  0.08002593 ... -0.07038905 -0.0283213
   0.04804676]
 [ 0.07221661 -0.04182237  0.05336686 ... -0.06942353  0.01795934
   0.06641504]
 ...
 [ 0.01586947 -0.05243036  0.0606509  ... -0.06435591  0.04215747
   0.06304204]
 [ 0.04141247  0.02588907 -0.0062563  ... -0.02162989  0.00910817
   0.03623575]
 [ 0.01578411 -0.02142678  0.00402448 ... -0.09605585 -0.06707881
   0.07970381]], shape=(8, 512), dtype=float32) 


Sentence :
A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic.
Converted to :
tf.Tensor(
[ 1.16849625e-02 -3.06057241e-02  6.11633621e-02  8.47723782e-02
 -5.83404116e-03  2.84162583e-03  2.59479079e-02  3.90261016e-03
 -5.55586144e-02  5.68111017e-02 -8.95012915e-03 -4.50471742e-03
 -6.06310219e-02  3.18566561e-02 -6.86047673e-02 -9.39451605e-02
 -4.23613675e-02  3.93056758e-02 -9.02280435e-02 -5.536637

#iii)ELMO

In [ ]:
import tensorflow_hub as hub
import tensorflow.compat.v1 as tf

tf.disable_eager_execution()
elmo = hub.Module("https://tfhub.dev/google/elmo/3", trainable=True)
  
embeddings = elmo(
    ["A paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.","  Almost  every  piece  of  writing you  do  that  is longer  than  a  few  sentences  should  be  organized  into paragraphs. "," This  is because paragraphs show a reader where the subdivisions of an essay begin and end, and thus help the reader see the organization of the essay and grasp its main points."," Paragraphs can  contain  many  different  kinds  of  information."," A paragraph could  contain  a  series  of  brief  examples  or  a  single  long illustration  of  a general  point. "," It  might  describe  a  place,  character,  or process;  narrate  a series of events; compare or contrast two or more things; classify items into categories;  or  describe  causes  and  effects. ","Regardless of the kind of information they contain, all paragraphs share certain characteristics. ","One of the most important of these is a topic sentence."],
    signature="default",
    as_dict=True)["elmo"]
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)
print(sess.run(embeddings))

Instructions for updating:
Use `tf.global_variables_initializer` instead.


[[[ 0.29287004 -0.14378013 -0.32574052 ... -0.39559263 -0.35758853
   -0.03588088]
  [-0.59441584  0.09640743  0.50537694 ...  0.22031914  0.269769
    0.46307266]
  [-0.1708326  -0.18744111 -0.27626696 ... -0.67550904  0.25389987
    0.6540271 ]
  ...
  [-0.0284084  -0.04353216  0.04130162 ...  0.02583168 -0.01429836
   -0.01650422]
  [-0.0284084  -0.04353216  0.04130162 ...  0.02583168 -0.01429836
   -0.01650422]
  [-0.0284084  -0.04353216  0.04130162 ...  0.02583168 -0.01429836
   -0.01650422]]

 [[ 0.3972119  -0.1509141   0.58700776 ... -0.44112715 -0.4109748
    0.15087722]
  [ 0.22274575 -0.12839264  0.01303142 ... -0.48178503 -0.6057211
    0.04756459]
  [-0.6277796  -0.454895    0.9650203  ... -0.6934171   0.2825519
    0.21852238]
  ...
  [-0.0284084  -0.04353216  0.04130162 ...  0.02583168 -0.01429836
   -0.01650422]
  [-0.0284084  -0.04353216  0.04130162 ...  0.02583168 -0.01429836
   -0.01650422]
  [-0.0284084  -0.04353216  0.04130162 ...  0.02583168 -0.01429836
   -0.01650

#iv) GP2

In [ ]:
gp2tokenizer = transformers.GPT2Tokenizer.from_pretrained('gpt2-large')
model = transformers.GPT2LMHeadModel.from_pretrained('gpt2-large')
res_vectors = gp2tokenizer.encode(string, add_special_tokens=False, return_tensors="pt")
print("shape=", res_vectors.shape)
print(res_vectors)

Downloading:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/666 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.25G [00:00<?, ?B/s]

shape= torch.Size([1, 171])
tensor([[   32,  7322,   318,   257,  2168,   286, 13439,   326,   389,  8389,
           290, 24870,    11,   290,   389,   477,  3519,   284,   257,  2060,
          7243,    13, 16699,   790,  3704,   286,  3597,   345,   466,   326,
           318,  2392,   621,   257,  1178, 13439,   815,   307,  8389,   656,
         23549,    13,   770,   318,   780, 23549,   905,   257,  9173,   810,
           262, 45944,  3279,   286,   281, 14268,  2221,   290,   886,    11,
           290,  4145,  1037,   262,  9173,   766,   262,  4009,   286,   262,
         14268,   290, 13180,   663,  1388,  2173,    13,  2547,  6111,    82,
           460,  3994,   867,  1180,  6982,   286,  1321,    13,   317,  7322,
           714,  3994,   257,  2168,   286,  4506,  6096,   393,   257,  2060,
           890, 20936,   286,   257,  2276,   966,    13,   632,  1244,  6901,
           257,  1295,    11,  2095,    11,   393,  1429,    26,  6664,   378,
           257,  2168,  

#v) BERT

In [ ]:
bert = hub.KerasLayer("https://tfhub.dev/google/nnlm-en-dim128/2")
embeddings = bert(sentences)
print(embeddings)
print("shape=",embeddings[0].shape)
print("The sentence in the paragraph:\n",sentences[0],"\nis converted into vector as :\n", embeddings[0])

tf.Tensor(
[[ 0.58439595  0.03570241  0.07089429 ...  0.16468506  0.01362591
  -0.17049454]
 [ 0.5674903  -0.03022472  0.14544438 ...  0.08465072  0.04284173
   0.03154207]
 [ 0.83034104  0.16388969 -0.03244966 ... -0.20251456  0.12385168
   0.08940062]
 ...
 [ 0.4393374   0.02327457  0.12449443 ...  0.05474888 -0.09519409
   0.00303834]
 [ 0.2909918   0.06627773  0.08403497 ... -0.10017543 -0.11646989
   0.00867226]
 [ 0.5081561  -0.04534546  0.09999924 ...  0.06375446 -0.00892024
  -0.03128232]], shape=(8, 128), dtype=float32)
shape= (128,)
The sentence in the paragraph:
 A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. 
is converted into vector as :
 tf.Tensor(
[ 0.58439595  0.03570241  0.07089429  0.07733776 -0.01214658 -0.12435579
 -0.07824828 -0.00274544 -0.17964575  0.21627969  0.03844824 -0.19277166
 -0.12646586  0.02667335 -0.13363229 -0.00374018 -0.06618838  0.00353754
 -0.21084203  0.18731229  0.06417363  0.03025784

##2Q. NAMED ENTITY RECOGNITION

In [ ]:
nlp = spacy.load("en_core_web_sm")
res = nlp(string)

for word in res.ents:
    print(word.text,word.label_)
    
print(spacy.explain('GPE'))

print(displacy.render(res,style="ent",jupyter=True))

two CARDINAL
One CARDINAL
Countries, cities, states


None


##Find similar sentences (repeated sentences) from the above paragraph? (Cosine Similarity, use BERT to encode)

In [ ]:
sbert_model = SentenceTransformer('bert-base-nli-mean-tokens')

se_embeddings = sbert_model.encode(sentences)
q1_vec= sbert_model.encode(sentences[0])

def cosine(u, v):
    return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

for sent in sentences:
    sim = cosine(q1_vec, sbert_model.encode([sent])[0])
    
    if sim>0.5:
        print("Sentence1 =",sentences[0],"\n \nSentence2=", sent, "\n\nsimilarity = ", sim,end="\n ----------------------------- \n")

Downloading:   0%|          | 0.00/391 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.95k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/399 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

Sentence1 = A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. 
 
Sentence2= A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. 

similarity =  1.0
 ----------------------------- 
Sentence1 = A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. 
 
Sentence2= Almost every piece of writing you do that is longer than a few sentences should be organized into paragraphs. 

similarity =  0.6477537
 ----------------------------- 
Sentence1 = A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. 
 
Sentence2= This is because paragraphs show a reader where the subdivisions of an essay begin and end, and thus help the reader see the organization of the essay and grasp its main points. 

similarity =  0.5238008
 ----------------------------- 
Sentence1 = A paragraph is a se

##POS TAGGING

In [ ]:
tokenized = sent_tokenize(string)
for i in tokenized:

    wordList = nltk.word_tokenize(i)
    wordList = [word for word in wordList if word not in stop_words]

    tagged = nltk.pos_tag(wordList)
 
    print(tagged)

[('A', 'DT'), ('paragraph', 'NN'), ('series', 'NN'), ('sentences', 'NNS'), ('organized', 'VBN'), ('coherent', 'NN'), (',', ','), ('related', 'VBN'), ('single', 'JJ'), ('topic', 'NN'), ('.', '.')]
[('Almost', 'RB'), ('every', 'DT'), ('piece', 'NN'), ('writing', 'VBG'), ('longer', 'JJR'), ('sentences', 'NNS'), ('organized', 'VBN'), ('paragraphs', 'NN'), ('.', '.')]
[('This', 'DT'), ('paragraphs', 'NN'), ('show', 'NN'), ('reader', 'NN'), ('subdivisions', 'NNS'), ('essay', 'VBP'), ('begin', 'JJ'), ('end', 'NN'), (',', ','), ('thus', 'RB'), ('help', 'NN'), ('reader', 'VB'), ('see', 'VB'), ('organization', 'NN'), ('essay', 'VB'), ('grasp', 'NN'), ('main', 'JJ'), ('points', 'NNS'), ('.', '.')]
[('Paragraphs', 'NNP'), ('contain', 'VBP'), ('many', 'JJ'), ('different', 'JJ'), ('kinds', 'NNS'), ('information', 'NN'), ('.', '.')]
[('A', 'DT'), ('paragraph', 'NN'), ('could', 'MD'), ('contain', 'VB'), ('series', 'NN'), ('brief', 'NN'), ('examples', 'VBZ'), ('single', 'JJ'), ('long', 'JJ'), ('illustr